name: Bug Report
description: Submit a bug report!
title: "[BUG] Untitled Bug Report"
labels: "bug"
assignees:
  - Lukas-Batema
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out this bug report! We will normally respond within 48 hours.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what you expected to happen.
      placeholder: Do you see what I see?
      value: "Oh no! A bug happened!"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - N/A (1)
        - N/A (2)
        - N/A (3)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Debug Log Output
      description: Please copy your debug logs and paste them here. This will automatically be put into a codeblock, so no need for any backticks!
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct]()
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true